formats:
  xml:
    enabled: true
    encoding: "utf-8"
    include_metadata: true
    use_cdata: true
  json:
    enabled: true
    structure:
      file: source_file
      folder: directory
      files: all_files
    fields:
      path: relative_path
      content: file_content
      filename: file_name
  markdown:
    enabled: true
    encoding: "utf-8"
  toml:
    enabled: false

output:
  default_format: markdown
  output_dir: ai_output
  filename_template: "ai_context_{{.timestamp}}.{{.extension}}"
  include_metadata: true
  ai_optimized: true
  ai_summary:
    enabled: true
    template_type: "detailed"
    file_path: ""
    content: "这是一个详细的AI摘要模板，包含项目概述、技术分析和代码质量评估。"
  ai_instructions:
    enabled: true
    template_type: "custom"
    file_path: ""
    content: "请重点关注代码的安全性、性能和可维护性。分析代码结构是否合理，是否存在潜在的安全漏洞，以及代码是否符合最佳实践。"

filters:
  max_file_size: "1MB"
  exclude_patterns:
    - "*.tmp"
    - "*.log"
    - "*.swp"
    - ".*"
    - "node_modules/"
    - "target/"
    - "dist/"
    - "build/"
    - ".env"
    - ".git/"
    - ".vscode/"
    - ".idea/"
    - "__pycache__/"
    - "*.pyc"
    - ".venv"
    - "*.class"
  exclude_binary: false