[formats]
  [formats.xml]
    enabled = true
    template = ""
    root_tag = "context"
    file_tag = "file"
    files_tag = "files"
    folder_tag = "folder"
    [formats.xml.fields]
      content = "content"
      filename = "filename"
      path = "path"
    [formats.xml.formatting]
      indent = "  "
      declaration = true
      encoding = "UTF-8"
  [formats.json]
    enabled = true
    template = ""
    [formats.json.structure]
      file = "file"
      folder = "folder"
    [formats.json.fields]
      content = "content"
      filename = "filename"
      path = "path"
  [formats.toml]
    enabled = true
    template = ""
    [formats.toml.structure]
      file_section = "file"
      folder_section = "folder"
    [formats.toml.fields]
      content = "content"
      filename = "filename"
      path = "path"
  [formats.markdown]
    enabled = true
    template = ""
    [formats.markdown.structure]
      code_block = "```"
      file_header = "##"
      folder_header = "###"
    [formats.markdown.fields]
      content = ""
      path = ""
    [formats.markdown.formatting]
      add_toc = false
      code_language = true
      separator = "\n\n"

[fields]
  [fields.custom_names]
    filecontent = "content"
    filename = "name"
    filepath = "path"
  [fields.filter]
    include = []
    exclude = []
  [fields.processing]
    max_length = 0
    add_line_numbers = false
    trim_whitespace = true
    code_highlight = false

[filters]
  max_file_size = "10MB"
  exclude_patterns = ["*.tmp", "*.log", "*.swp", ".*"]
  include_patterns = []
  max_depth = 0
  follow_symlinks = false

[output]
  default_format = "xml"
  output_dir = ""
  filename_template = "context_{{.timestamp}}.{{.extension}}"
  timestamp_format = "20060102_150405"

[ui]
  [ui.selector]
    show_hidden = false
    show_size = true
    show_modified = false
  [ui.autocomplete]
    enabled = true
    min_chars = 1
    max_suggestions = 10
