# 代码上下文生成器 - 基础配置文件示例
# 适用于大多数项目的标准配置

[output]
format = "json"          # 输出格式: json, xml, toml, markdown
encoding = "utf-8"       # 文件编码
pretty = true            # 美化输出
output_dir = "./output"  # 输出目录
filename_template = "context_{{.Timestamp}}.{{.Format}}"  # 文件名模板

[file_processing]
include_hidden = false   # 是否包含隐藏文件
include_content = false  # 是否包含文件内容
include_hash = false     # 是否包含文件哈希值
max_file_size = 10485760  # 最大文件大小 (10MB)
max_depth = 0            # 最大扫描深度 (0表示无限制)
buffer_size = 8192       # 缓冲区大小
workers = 4              # 并发工作线程数

# 排除模式 (支持glob模式)
exclude_patterns = [
    # 编译产物
    "*.exe", "*.dll", "*.so", "*.dylib", "*.a", "*.lib",
    
    # Python
    "*.pyc", "*.pyo", "*.pyd", "__pycache__", "*.egg-info", ".pytest_cache",
    
    # Node.js
    "node_modules", "npm-debug.log", "yarn-error.log", ".npm", ".yarn",
    
    # 版本控制
    ".git", ".svn", ".hg", ".bzr", "_darcs", "CVS",
    
    # IDE和编辑器
    ".vscode", ".idea", "*.swp", "*.swo", "*~", ".DS_Store", "Thumbs.db",
    
    # 临时文件
    "*.tmp", "*.temp", "*.log", "*.bak", "*.backup",
    
    # 构建目录
    "dist", "build", "target", "out", "bin", "obj",
    
    # 依赖管理
    "vendor", "packages", "composer.lock", "package-lock.json",
    
    # 文档生成
    "docs/_build", "site", ".tox"
]

# 包含模式 (如果指定，则只包含匹配的文件)
include_patterns = []

[ui]
theme = "default"        # 界面主题
show_progress = true     # 显示进度条
show_size = true         # 显示文件大小
show_date = true         # 显示修改日期
show_preview = true      # 显示预览
auto_complete = true     # 自动补全
confirm_deletion = true  # 删除确认

[performance]
cache_enabled = true     # 启用缓存
cache_size = 100         # 缓存大小
memory_limit = 1073741824  # 内存限制 (1GB)

[logging]
level = "info"           # 日志级别: debug, info, warn, error
file_path = ""           # 日志文件路径 (空表示控制台输出)
max_size = 10            # 日志文件最大大小 (MB)
max_backups = 3          # 保留的旧日志文件数
max_age = 7              # 日志文件保留天数

[formats.json]
enabled = true
indent = "  "
sort_keys = true
escape_html = false

[formats.xml]
enabled = true
indent = "  "
use_cdata = false
declaration = true

[formats.toml]
enabled = true
indent = "  "

[formats.markdown]
enabled = true
template = "default"     # 模板: default, compact, detailed
include_toc = true       # 包含目录
heading_level = 2        # 标题级别
code_highlight = true    # 代码高亮

# 自定义字段映射 (可选)
[field_mapping]
# path = "file_path"
# size = "file_size"
# modified = "last_modified"

# 全局字段 (可选)
[global_fields]
# project_name = "MyProject"
# version = "1.0.0"
# author = "Your Name"
# description = "Project description"