# 代码上下文生成器 - 项目文档生成配置
# 适用于生成完整的项目文档，包含文件内容和结构信息

[output]
format = "markdown"      # 使用Markdown格式，便于阅读和分享
encoding = "utf-8"
pretty = true
output_dir = "./docs"    # 输出到docs目录
filename_template = "{{.ProjectName}}_documentation_{{.Date}}.md"

[file_processing]
include_hidden = false
include_content = true   # 包含文件内容，生成完整文档
include_hash = true      # 包含哈希值，用于完整性验证
max_file_size = 524288   # 最大512KB，避免包含过大的文件
max_depth = 5            # 限制扫描深度，避免过深的目录结构
buffer_size = 8192
workers = 6              # 增加工作线程数，提高处理速度

# 排除模式 - 针对文档生成优化
exclude_patterns = [
    # 大文件和二进制文件
    "*.exe", "*.dll", "*.so", "*.dylib", "*.bin", "*.dat", "*.db",
    
    # 图片和媒体文件
    "*.jpg", "*.jpeg", "*.png", "*.gif", "*.svg", "*.ico", "*.mp4", "*.mp3",
    
    # 压缩包和归档
    "*.zip", "*.rar", "*.7z", "*.tar", "*.gz", "*.bz2",
    
    # 临时文件和缓存
    "*.tmp", "*.temp", "*.cache", "*.log", "*.bak", "*.backup", "*.old",
    
    # 版本控制
    ".git", ".gitignore", ".gitattributes",
    ".svn", ".hg", ".bzr", "_darcs", "CVS",
    
    # 依赖管理
    "node_modules", "vendor", "packages", ".npm", ".yarn",
    "go.sum", "go.mod", "package-lock.json", "yarn.lock",
    
    # 构建产物
    "dist", "build", "target", "out", "bin", "obj", "lib",
    
    # IDE和编辑器配置
    ".vscode", ".idea", "*.swp", "*.swo", "*~",
    
    # 操作系统文件
    ".DS_Store", "Thumbs.db", "desktop.ini",
    
    # Python相关
    "__pycache__", "*.pyc", "*.pyo", "*.pyd",
    ".pytest_cache", "*.egg-info", ".eggs",
    
    # 测试覆盖和报告
    ".coverage", "htmlcov", "coverage.xml", ".tox",
    
    # 文档生成产物
    "docs/_build", "site", ".tox"
]

# 重点关注源代码和文档文件
include_patterns = [
    "*.go", "*.py", "*.js", "*.ts", "*.jsx", "*.tsx",
    "*.java", "*.cpp", "*.c", "*.h", "*.hpp",
    "*.rb", "*.php", "*.rs", "*.swift", "*.kt",
    "*.md", "*.txt", "*.rst", "*.adoc",
    "*.json", "*.yaml", "*.yml", "*.toml", "*.xml",
    "*.html", "*.css", "*.scss", "*.sass", "*.less",
    "*.sql", "*.sh", "*.bat", "*.ps1",
    "Makefile", "Dockerfile", "docker-compose.yml",
    "LICENSE", "README*", "CHANGELOG*", "CONTRIBUTING*"
]

[ui]
theme = "default"
show_progress = true
show_size = true
show_date = true
show_preview = true

[performance]
cache_enabled = true
cache_size = 200
memory_limit = 2147483648  # 2GB内存限制

[logging]
level = "info"
file_path = "./logs/documentation.log"
max_size = 50
max_backups = 5
max_age = 30

[formats.markdown]
enabled = true
template = "detailed"    # 使用详细模板
include_toc = true       # 包含目录，便于导航
heading_level = 1        # 从一级标题开始
code_highlight = true    # 启用代码高亮
include_metadata = true  # 包含元数据信息

# 自定义字段映射，优化文档结构
[field_mapping]
path = "文件路径"
size = "文件大小"
modified = "修改时间"
content = "文件内容"
hash = "哈希值"
extension = "文件类型"

# 全局字段，添加到每个文档
[global_fields]
documentation_type = "项目文档"
generated_by = "代码上下文生成器"
version = "1.0.0"
documentation_version = "1.0"
language = "zh-CN"

# 文档特定配置
[documentation]
project_name = "{{.ProjectName}}"  # 项目名称（自动检测）
project_description = "自动生成的项目文档"
include_file_tree = true         # 包含文件树结构
include_statistics = true          # 包含统计信息
include_summary = true             # 包含摘要信息
group_by_type = true              # 按文件类型分组
sort_by_size = false              # 按文件大小排序（false表示按路径排序）