formats:
  xml:
    enabled: true
    structure:
      file: file
      files: files
      folder: folder
      root: context
    fields:
      content: content
      filename: filename
      path: path
    template: ""
    formatting: {}
  json:
    enabled: true
    structure:
      file: file
      folder: folder
    fields:
      content: content
      filename: filename
      path: path
    template: ""
    formatting: {}
  toml:
    enabled: true
    structure:
      file_section: file
      folder_section: folder
    fields:
      content: content
      filename: filename
      path: path
    template: ""
    formatting: {}
  markdown:
    enabled: true
    structure:
      code_block: "```"
      file_header: "##"
      folder_header: "###"
    fields: {}
    template: ""
    formatting:
      add_toc: false
      code_language: true
      separator: |+
        

fields:
  custom_names:
    filecontent: content
    filename: name
    filepath: path
  filter:
    include: []
    exclude: []
  processing:
    max_length: 0
    add_line_numbers: false
    trim_whitespace: true
    code_highlight: false
filters:
  max_file_size: 10MB
  exclude_patterns:
  - "*.tmp"
  - "*.log"
  - "*.swp"
  - .*
  - node_modules/
  - target/
  - dist/
  - build/
  - .env
  - .git/
  - .vscode/
  - .idea/
  - __pycache__/
  - "*.pyc"
  - .venv
  - "*.class"
  include_patterns: []
  max_depth: 0
  follow_symlinks: false
  exclude_binary: true
output:
  format: "markdown"
  encoding: "utf-8"
  includemetadata: true
  includestatistics: true
  templatepath: ""
  default_format: xml
  output_dir: ""
  filename_template: context_{{.timestamp}}.{{.extension}}
  timestamp_format: "20060102_150405"

file_processing:
  includehidden: false
  includecontent: true
  maxfilesize: "1MB"
  binarydetection: true
  encodingdetection: true
  maxdepth: 0
  excludepatterns:
    - ".git"
    - "node_modules"
    - "*.exe"
    - "*.dll"
    - "*.so"
    - "*.dylib"
    - "*.class"
    - "*.pyc"
    - "__pycache__"
    - ".DS_Store"
    - "Thumbs.db"
  includepatterns: []
  includehash: false
performance:
  maxworkers: 0
  buffersize: 4096
  cachesize: 1000
  cacheenabled: false
logging:
  level: "info"
  format: "text"
  output: "stdout"
  filepath: ""
  maxsize: 0
  maxbackups: 0
  maxage: 0
